[package]
name = "depguard-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "depguard"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true

depguard-app = { path = "../depguard-app" }
depguard-domain = { path = "../depguard-domain" }
depguard-render = { path = "../depguard-render" }
depguard-settings = { path = "../depguard-settings" }
depguard-types = { path = "../depguard-types" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
serde_json.workspace = true
cucumber.workspace = true
async-trait.workspace = true
futures.workspace = true
jsonschema.workspace = true
walkdir.workspace = true
time.workspace = true

[[test]]
name = "bdd"
harness = false
