[package]
name = "depguard-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Use case orchestration for depguard (check, md, annotations, explain)"

[dependencies]
depguard-types.path = "../depguard-types"
depguard-domain.path = "../depguard-domain"
depguard-repo.path = "../depguard-repo"
depguard-settings.path = "../depguard-settings"
depguard-render.path = "../depguard-render"

anyhow.workspace = true
camino.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
tempfile.workspace = true
