[package]
name = "depguard-domain"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror.workspace = true

depguard-types = { path = "../depguard-types" }

[dev-dependencies]
proptest.workspace = true
