[package]
name = "depguard-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
depguard-types = { path = "../depguard-types" }

[dev-dependencies]
insta.workspace = true
time.workspace = true
