[package]
name = "depguard-types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
camino.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
time.workspace = true
